Django_ORM/practice/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('blog/<int:blog_id>/', views.detail, name='detail'),
    path('blog/new/', views.new, name='new'),
    path('blog/create/', views.create, name='create'),
    path('blog/edit/<int:blog_id>/', views.edit, name='edit'),
    path('blog/update/<int:blog_id>/', views.update, name='update'),
    path('blog/delete/<int:blog_id>/', views.delete, name='delete'),
    path('blog/create_comment/<int:blog_id>/', views.create_comments, name='create_comment'),
    path('blog/new_comment/<int:blog_id>/', views.new_comment, name='new_comment'),
    path('like/<int:blog_pk>/', views.likes, name='like') #! 좋아요 추가/삭제 때 사용
]

Django_ORM/practice/practice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_ORM/practice/blog/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    image = models.ImageField(upload_to='blog/', null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='blogs') #! 좋아요 기능 추가
    tag = models.ManyToManyField(to='Tag', blank=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_blogs', blank=True)
    #작성자와 블로그는 1:N 관계 (작성자1명 게시글 여러개)

    class Meta:
        db_table = 'blog'
    
    def __str__(self):
        return self.title
    
    def summary(self):
        return self.content[:100]

# 댓글
class Comment(models.Model):
    content = models.CharField(max_length=200)
    create_at = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True, related_name='comments')
    # 1:N관계 - 하나의 글에 여러개의 댓글 달릴 수 있음
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='comments')
    # 1:N관계 - 한 명의 작성자가 여러개의 댓글 작성할 수 있음

    class Meta:
        db_table = 'comment'
    
    def __str__(self):
        return self.content + " | " + str(self.author)

# 태그
class Tag(models.Model):
    name = models.CharField(max_length=10)

    class Meta:
        db_table = 'tag'
    
    def __str__(self):
        return self.name

Django_ORM/practice/blog/forms.py
from django import forms
from .models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content']

Django_ORM/practice/blog/views.py
from django.contrib.auth.decorators import login_required #! 추가된 코드
from django.shortcuts import render,get_object_or_404,redirect
from django.core.paginator import Paginator
from .models import Blog, Comment, Tag
from .forms import BlogForm
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_POST

User = get_user_model()

def home(request):
    blogs = Blog.objects.all()
    paginator = Paginator(blogs, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,'home.html',{'page_obj':page_obj})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    comments = Comment.objects.filter(blog=blog)
    tags = blog.tag.all()
    return render(request,'detail.html',{'blog':blog, 'comments':comments, 'tags':tags})

def new(request):
    tags = Tag.objects.all()
    return render(request,'new.html', {'tags':tags})

# def create(request):
#     new_blog = Blog()
#     new_blog.title = request.POST.get('title')
#     new_blog.content = request.POST.get('content')
#     new_blog.image = request.FILES.get('image')
#     new_blog.author = request.user
#     new_blog.save()
#     tags = request.POST.getlist('tags')
#     for tag_id in tags:
#         tag = Tag.objects.get(id=tag_id)
#         new_blog.tag.add(tag)

#     return redirect('detail', new_blog.id)

@login_required
def create(request):
    if request.method == 'POST':
        new_blog = Blog()
        new_blog.title = request.POST.get('title')
        new_blog.content = request.POST.get('content')
        if 'image' in request.FILES:
            new_blog.image = request.FILES.get('image')
        new_blog.author = request.user
        new_blog.save()
        tags = request.POST.getlist('tags')
        for tag_id in tags:
            tag = Tag.objects.get(id=tag_id)
            new_blog.tag.add(tag)
        return redirect('blog:detail', new_blog.id)
    else:
        tags = Tag.objects.all()
        return render(request, 'new.html', {'tags': tags})

def edit(request, blog_id):
    edit_blog = get_object_or_404(Blog, pk=blog_id)
    if edit_blog.author != request.user:
        return redirect('blog:home')
    return render(request, 'edit.html', {'edit_blog':edit_blog})

def update(request, blog_id):
    old_blog = get_object_or_404(Blog, pk=blog_id)
    old_blog.title = request.POST.get('title')
    old_blog.content = request.POST.get('content')
    old_blog.image = request.FILES.get('image')
    old_blog.save()
    return redirect('blog:detail', old_blog.id)

    if form.is_valid():
        new_blog = form.save(commit=False)
        new_blog.save()
        return redirect('detail', old_blog.id)

    return render(request, 'new.html', {'old_blog':old_blog})

def delete(request, blog_id):
    delete_blog = get_object_or_404(Blog, pk=blog_id)
    delete_blog.delete()
    return redirect('blog:home')

def create_comments(request, blog_id):
    comment = Comment()
    comment.content = request.POST.get('content')
    comment.blog = get_object_or_404(Blog, pk=blog_id)
    # blog가 없으면 댓글도 있으면 안되니까 get object or 404
    comment.author = request.user
    comment.save()

    return redirect('blog:detail', blog_id)

def new_comment(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'new_comment.html', {'blog':blog})

#! 좋아요 기능 함수
@require_POST
def likes(request, blog_pk):
    if request.user.is_authenticated:
        blog = get_object_or_404(Blog, pk=blog_pk)
        if request.user in blog.like_users.all():
            blog.like_users.remove(request.user)
        else:
            blog.like_users.add(request.user)
        return redirect('blog:detail', blog_pk) #* 좋아요 추가/삭제 후 상세 페이지로
    return redirect('login') #* 로그인 되지 않았으면 로그인 페이지로

Django_ORM/practice/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title %}</title>
    {% block extrahead %} {% endblock extrahead %}
  </head>

  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

Django_ORM/practice/blog/templates/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>블로그 상세 페이지</title>
        <style>
            body {
                display: flex;
                flex-direction: column;
                align-items: center;
                text-align: center;
            }
            img {
                height: 400px;
                width: 550px;
            }
            hr {
                width: 70%;
                height: 0.3px;
            }
            a {
                text-decoration: none;
                display: inline-block;
                width: 10rem;
                padding: 0.2rem;
                margin: 0.5rem;
                border-radius: 0.5rem;
                background-color: #f2f2f2;
                color: black;
            }
            a:hover { background-color: #e6e6e6; }
            .nav {
                display: flex;
                justify-content: space-between;
                width: 30%;
            }
        </style>
    </head>
    <body>
        <h1>블로그 상세 페이지</h1>
        <br />
        <hr />
        <h2>{{blog.title}}</h2>
        <hr />
        {% if tags %}
        <h3 style="margin: 10px">태그</h3>
        <div style="display: flex">
            {% for tag in tags %}
            <p style="margin: 10px">{{ tag }}</p>
            &nbsp; {% endfor %}
        </div>
        {% endif %}

        <hr />
        <p>{{blog.content}}</p>

        {% if blog.image %}
        <img src="{{blog.image.url}}" alt="이미지" />
        {% endif %}

        <p>{{blog.created_at}}</p>

        <div class="nav">
            <a href="{% url 'blog:home' %}">홈</a>
            <a href="{% url 'blog:edit' blog.id %}">수정하기</a>
            <a href="{% url 'blog:delete' blog.id %}">삭제하기</a>
        </div>

        <hr />

        <div>
            <form action="{% url 'blog:like' blog.pk %}" method="POST">
                {% csrf_token %}
                {% if user in blog.like_users.all %}
                    <input type="submit" value="♡ 좋아요 취소" />
                {% else %}
                    <input type="submit" value="♥ 좋아요" />
                {% endif %}
            </form>
        </div>

        <a href="{% url 'blog:new_comment' blog.id %}">댓글 달기</a>

        {% if comments %} {% for comment in comments %}
        <hr />
        <p>{{comment.content}}</p>
        <p>{{comment.created_at}} 댓글쓴이: {{ comment.author }}</p>
        {% endfor %} {% endif %}
    </body>
</html>

Django_ORM/practice/blog/templates/edit.html
<h1>edit 페이지</h1>

<form method="POST" action="{% url 'update' edit_blog.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="title" value="{{edit_blog.title}}" />
    <textarea name="content" id="" cols="30">{{edit_blog.content}}</textarea>
    <input type="file" name="image" />
    <input type="submit" value="수정하기" />
</form>

<a href="{% url 'home' %}">홈</a>
<a href="{% url 'delete' edit_blog.id %}">삭제하기</a>

Django_ORM/practice/blog/templates/home.html
{% extends "base.html" %} {% load static %} {% block title %} 블로그 홈페이지!!
{% endblock title %} {% block extrahead %}
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}" />
{% endblock extrahead %} {% block content %}

<h1>
  LIKELION 12 Blog Project
  <img src="{% static 'blog/img/emoticon.png' %}" alt="이모티콘" />
</h1>
<div>
  {% if user.is_authenticated %}
  <a href="users/logout">로그아웃</a>
  <h1>환영합니다! {{user.username}} 님</h1>
  <a href="{% url 'profile' user.id %}">내 프로필 보기</a>
  <a class="new-post__button" href="{% url 'blog:new' %}">새 글 작성하기</a>
  {% else %}
  <a href="users/signup">회원가입</a>
  <a href="users/login">로그인</a>
  {% endif %}
</div>
<div>
  {% for blog in page_obj %}
  <a href="{% url 'blog:detail' blog.id %}">
    <h2>{{blog.title}}</h2>
    <p>글쓴이: {{blog.author}}</p>
    <p>{{blog.summary}}</p>
    <p>{{blog.created_at}}</p>
  </a>
  {% endfor %}
</div>

<span>
  {% if page_obj.has_previous %}
  <a href="?page=1">처음으로</a>
  <a href="?page={{page_obj.previous_page_number}}">이전</a>
  {% endif %}

  <p>{{page_obj.number}}</p>
  <p>/</p>
  <p>{{page_obj.paginator.num_pages}}</p>

  {% if page_obj.has_next %}
  <a href="?page={{page_obj.next_page_number}}">다음</a>
  <a href="?page={{page_obj.paginator.num_pages}}">마지막으로</a>
  {% endif %}
</span>
{% endblock content %}

Django_ORM/practice/blog/templates/new.html
<!DOCTYPE html>
<html>
<head>
    <title>My Web Page</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            text-align: center;
        }
        container {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }
        .input, #tags { width: 75%; }
        a, .btn {
            text-decoration: none;
            display: inline-block;
            width: 10rem;
            padding: 0.2rem;
            margin: 0.5rem;
            border-radius: 0.5rem;
            background-color: #f2f2f2;
            color: black;
            outline: none;
            border: none;
            font-size: 1rem;
        }
        .btn { margin-top: 1rem; }
        a:hover, .btn:hover { background-color: #e6e6e6; }
    </style>
</head>
<body>
    <h1>새 글 작성하기</h1>
    <form action="{%url 'blog:create'%}" method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        <div class="container">
            제목 : <input type="text" name="title" value="" class="input" /> <br /><br/>
            본문 :
            <textarea name="content" id="" cols="30" rows="10" class="input"></textarea> <br />
            &nbsp;&nbsp;&nbsp;사진 : <input type="file" name="image" /><br />
            <label for="tags">Tags:</label>
            <select name="tags" id="tags" multiple>
                {% for tag in tags %}
                <option value="{{ tag.id }}">{{ tag.name }}</option>
                {% endfor %}
            </select> <br />
            <input type="submit" value="작성하기" class="btn"/> <br />
        </divcla>
    </form>
    <a href="{% url 'blog:home' %}">홈</a>

</body>
</html>

Django_ORM/practice/blog/templates/new_comment.html
<h1>새 댓글 작성하기</h1>
<form action="{%url 'create_comment' blog.id %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %} 댓글 :
  <textarea name="content" id="" cols="30" rows="10"></textarea>
  <input type="submit" value="댓글 달기" />
</form>

<a href="{% url 'home' %}">홈</a>